### ISSUE TITLE
定義 Clients 清單的歸屬問題

### ISSUE THREAD

**Issue by fntsrlike** [NCU-Anti-Java/NCU_2015_Anti-Java#20]
Server 模組應該不會知道確定進入房間且開始遊戲的 Client 有誰？這部分應該是 Scene 模組在切換場景時（開始遊戲）時才會知道？所以 Scene 模組要跟 Server 模組確認，對嗎？

**Comment by fntsrlike** [comment]
@tjjh89017 @Sharknevercries @YWJamesLin

**Comment by fntsrlike** [comment]
是不是有需要定義一個 `Client` 的類別？

若需，這名稱會和 **Client 模組**重名，建議可以改用 `Player` 之類的類別名稱取代。像這樣：

``` java
public class Player {
    private InetAddress address;
    private UUID clientID;
    private Object tag;  

    // TODO: getter & setter
}
```

**Comment by davy-tw** [comment]
Great 再加一個 `void setTag(Object obj)` 跟 `Object getTag()` 讓 Scene 可以放其他額外的資訊。

**Comment by fntsrlike** [comment]
:+1: done

**Comment by fntsrlike** [comment]
這部分似乎還沒有定論

Player 何時會產生，是客戶端自己建立傳給伺服器呢？還是伺服器收到客戶端的 ClientID 時建立呢？還是由 Scene 負責呢？

Player 會要在建構的時候就傳入 IP 和 ClientID 嗎？

**Comment by davy-tw** [comment]
Server handle it

**Comment by fntsrlike** [comment]
PR #35

**Comment by davy-tw** [comment]
merged
