### ISSUE TITLE
Input 的 repeat rate 太高

### ISSUE THREAD

**Issue by davy-tw** [NCU-Anti-Java/NCU_2015_Anti-Java#46]
現在是一次 update 之後如果按鍵還是有持續按下的話就可以觸發 `Input#isPressing(Key)`
但是這樣 rate 太高了，1 秒可以按 60 次有些太噁心

所以建議參考別人的做法 https://github.com/Ancurio/mkxp/blob/master/src/input.cpp#L627

在持續按下 23 tick 之後，每 6 tick 觸發一次 `Input#isRepeat`(Key) （第 24 tick 就會觸發了）
（這裏修改名稱以符合「到達某個臨界後重複觸發的規則」，原來的 `Input#isPressing(Key)` 還是可以留著）

@firejox 覺得如何？

**Comment by firejox** [comment]
@david50407 
覺得可以

**Comment by davy-tw** [comment]
那就交給你了 XD

**Comment by fntsrlike** [comment]
:+1:

**Comment by firejox** [comment]
@david50407 
done in feature/input
幫忙檢查一下
