### ISSUE TITLE
Viewport 的繪畫順序問題

### ISSUE THREAD

**Issue by Sharknevercries** [NCU-Anti-Java/NCU_2015_Anti-Java#83]
@david50407 Viewport的繪畫順序好像沒有根據它的 z 值做先後繪製的部分，這樣在StageScene的前、中、後景會失去意義 (後景可能因為繪畫順序仍然蓋過前景)

**Comment by davy-tw** [comment]
有吧，我修過了耶

z 越大越上面噢
