### ISSUE TITLE
[Note] Network Class Issue

### ISSUE THREAD

**Issue by tjjh89017** [NCU-Anti-Java/NCU_2015_Anti-Java#94]
Is there still `mServer.start()` and `mServer.bind()` in `Network.start(InetAddress)` ?

**Comment by tjjh89017** [comment]
記得要跟你現在的 code，做比對，沒有用到的就直接跳過就好
JoinScene 在操作 Join 時，沒有先 client.start(InetAddress)，所以基本上會 hang 在 client.send()，所以當時 Checking Thread 沒有啟動也是因為卡在那邊，或是直接噴 exception (但是沒有看到 error msg，可能被某個 catch 吃到了)。

如果使用 start InetAddress，Network class 中 start(InetAddress)不應該有 mServer.start跟bind，不然就直接卡住，或是噴 exception (但是沒有看到 error msg，可能被某個 catch 吃到了)。

**Comment by fntsrlike** [comment]
![2016-01-03 1 01 43](https://cloud.githubusercontent.com/assets/2680724/12075268/958c98a6-b1b5-11e5-8a53-48285dcb6911.png)
