### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by tjjh89017** [NCU-Anti-Java/NCU_2015_Anti-Java#98]
![image](https://cloud.githubusercontent.com/assets/2821179/12078160/75d0377e-b242-11e5-800d-05dfef18dfc7.png)

不一定觸發，問題尋找中

**Comment by firejox** [comment]
原因在Join Thread跟 Main Thread發生 race condition
導致join threads拿request時 正好Main thread在update 中 clear request

**Comment by tjjh89017** [comment]
got it
想想看怎麼解決這問題@@

**Comment by tjjh89017** [comment]
Fix issue

**Comment by fntsrlike** [comment]
喔不，是 race condition。QwQ
